version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@ngneat/tailwind"
    versions:
    - 6.0.2
    - 6.0.3
    - 7.0.1
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
  - dependency-name: purgecss
    versions:
    - 4.0.0
  - dependency-name: "@types/express"
    versions:
    - 4.17.11
  - dependency-name: postcss
    versions:
    - 8.2.4
